--- Makefile	2022-11-21 12:12:53.908107383 +0800
+++ Makefile	2022-11-21 12:12:53.916107295 +0800
@@ -2,7 +2,7 @@
 # Project Information
 # -----------------------------------------------------------------------
 
-PROJECT_IDX	= 4
+PROJECT_IDX	= 5
 
 # -----------------------------------------------------------------------
 # Host Linux Variables
@@ -53,6 +53,8 @@ QEMU_OPTS       = -nographic -machine vi
                      -D $(QEMU_LOG_FILE) -d oslab
 QEMU_DEBUG_OPT  = -s -S
 QEMU_SMP_OPT	= -smp 2
+QEMU_NET_OPT    = -netdev tap,id=mytap,ifname=tap0,script=${DIR_QEMU}/etc/qemu-ifup,downscript=${DIR_QEMU}/etc/qemu-ifdown \
+                    -device e1000,netdev=mytap
 
 # -----------------------------------------------------------------------
 # UCAS-OS Entrypoints and Variables
@@ -66,7 +68,7 @@ DIR_KERNEL      = ./kernel
 DIR_LIBS        = ./libs
 DIR_TINYLIBC    = ./tiny_libc
 DIR_TEST        = ./test
-DIR_TEST_PROJ   = $(DIR_TEST)/test_project$(PROJECT_IDX)/S_CORE
+DIR_TEST_PROJ   = $(DIR_TEST)/test_project$(PROJECT_IDX)
 
 BOOTLOADER_ENTRYPOINT   = 0x50200000
 KERNEL_ENTRYPOINT       = 0xffffffc050202000
@@ -127,7 +129,7 @@ clean:
 
 floppy:
 	sudo fdisk -l $(DISK)
-	sudo dd if=$(DIR_BUILD)/image of=$(DISK)2 conv=notrunc
+	sudo dd if=$(DIR_BUILD)/image of=$(DISK)3 conv=notrunc
 
 asm: $(ELF_BOOT) $(ELF_MAIN) $(ELF_USER)
 	for elffile in $^; do $(OBJDUMP) -d $$elffile > $(notdir $$elffile).txt; done
@@ -141,16 +143,28 @@ run:
 run-smp:
 	$(QEMU) $(QEMU_OPTS) $(QEMU_SMP_OPT)
 
+run-net:
+	-@sudo kill `sudo lsof | grep tun | awk '{print $$2}'`
+	sudo $(QEMU) $(QEMU_OPTS) $(QEMU_NET_OPT)
+
 debug:
 	$(QEMU) $(QEMU_OPTS) $(QEMU_DEBUG_OPT)
 
 debug-smp:
 	$(QEMU) $(QEMU_OPTS) $(QEMU_SMP_OPT) $(QEMU_DEBUG_OPT)
 
+debug-net:
+	-@sudo kill `sudo lsof | grep tun | awk '{print $$2}'`
+	sudo $(QEMU) $(QEMU_OPTS) $(QEMU_DEBUG_OPT) $(QEMU_NET_OPT)
+
+viewlog:
+	@if [ ! -e $(QEMU_LOG_FILE) ]; then touch $(QEMU_LOG_FILE); fi;
+	@tail -f $(QEMU_LOG_FILE)
+
 minicom:
 	sudo $(MINICOM) -D $(TTYUSB1)
 
-.PHONY: all dirs clean floppy asm gdb run debug viewlog minicom
+.PHONY: all dirs clean floppy asm gdb run debug viewlog minicom run-net debug-net
 
 # -----------------------------------------------------------------------
 # UCAS-OS Rules
