--- Makefile	2022-10-15 22:50:09.564565164 +0800
+++ Makefile	2022-10-15 22:50:09.568565138 +0800
@@ -2,7 +2,7 @@
 # Project Information
 # -----------------------------------------------------------------------
 
-PROJECT_IDX	= 1
+PROJECT_IDX	= 3
 
 # -----------------------------------------------------------------------
 # Host Linux Variables
@@ -52,6 +52,7 @@ QEMU_OPTS       = -nographic -machine vi
                      -monitor telnet::45454,server,nowait -serial mon:stdio \
                      -D $(QEMU_LOG_FILE) -d oslab
 QEMU_DEBUG_OPT  = -s -S
+QEMU_SMP_OPT	= -smp 2
 
 # -----------------------------------------------------------------------
 # UCAS-OS Entrypoints and Variables
@@ -65,7 +66,7 @@ DIR_KERNEL      = ./kernel
 DIR_LIBS        = ./libs
 DIR_TINYLIBC    = ./tiny_libc
 DIR_TEST        = ./test
-DIR_TEST_PROJ   = $(DIR_TEST)/test_project$(PROJECT_IDX)
+DIR_TEST_PROJ   = $(DIR_TEST)/test_project$(PROJECT_IDX)/S_CORE
 
 BOOTLOADER_ENTRYPOINT   = 0x50200000
 KERNEL_ENTRYPOINT       = 0x50201000
@@ -100,7 +101,8 @@ SRC_LIBC    = $(wildcard ./tiny_libc/*.c
 OBJ_LIBC    = $(patsubst %.c, %.o, $(foreach file, $(SRC_LIBC), $(DIR_BUILD)/$(notdir $(file))))
 LIB_TINYC   = $(DIR_BUILD)/libtinyc.a
 
-SRC_USER    = $(wildcard $(DIR_TEST_PROJ)/*.c)
+SRC_SHELL	= $(DIR_TEST)/shell.c
+SRC_USER    = $(SRC_SHELL) $(wildcard $(DIR_TEST_PROJ)/*.c)
 ELF_USER    = $(patsubst %.c, %, $(foreach file, $(SRC_USER), $(DIR_BUILD)/$(notdir $(file))))
 
 # -----------------------------------------------------------------------
@@ -135,9 +137,14 @@ gdb:
 run:
 	$(QEMU) $(QEMU_OPTS)
 
+run-smp:
+	$(QEMU) $(QEMU_OPTS) $(QEMU_SMP_OPT)
+
 debug:
 	$(QEMU) $(QEMU_OPTS) $(QEMU_DEBUG_OPT)
 
+debug-smp:
+	$(QEMU) $(QEMU_OPTS) $(QEMU_SMP_OPT) $(QEMU_DEBUG_OPT)
 
 minicom:
 	sudo $(MINICOM) -D $(TTYUSB1)
@@ -167,6 +174,10 @@ $(DIR_BUILD)/%: $(DIR_TEST_PROJ)/%.c $(O
 	$(CC) $(USER_CFLAGS) -o $@ $(OBJ_CRT0) $< $(USER_LDFLAGS) -Wl,--defsym=TEXT_START=$(USER_ENTRYPOINT) -T riscv.lds
 	$(eval USER_ENTRYPOINT := $(shell python3 -c "print(hex(int('$(USER_ENTRYPOINT)', 16) + int('0x10000', 16)))"))
 
+$(DIR_BUILD)/%: $(DIR_TEST)/%.c $(OBJ_CRT0) $(LIB_TINYC) riscv.lds
+	$(CC) $(USER_CFLAGS) -o $@ $(OBJ_CRT0) $< $(USER_LDFLAGS) -Wl,--defsym=TEXT_START=$(USER_ENTRYPOINT) -T riscv.lds
+	$(eval USER_ENTRYPOINT := $(shell python3 -c "print(hex(int('$(USER_ENTRYPOINT)', 16) + int('0x10000', 16)))"))
+
 elf: $(ELF_BOOT) $(ELF_MAIN) $(LIB_TINYC) $(ELF_USER)
 
 .PHONY: elf
